### ISSUE TITLE
GetStreamByChannel not work.

### ISSUE THREAD

**Issue by dimensi** [knspriggs/go-twitch#32]
Hi! I new in golang. Try use your library.
```go
	twitchSession, err := twitch.NewSession(twitch.NewSessionInput{ClientID: "eaaygbr09v6tn9j5ser40hgqrj7cli"})

	if err != nil {
		log.Fatalln(err)
	}

	stream := twitch.GetStreamByChannelInputType{Channel: "90810861"}

	resp, err := twitchSession.GetStreamByChannel(&stream)

	if err != nil {
		log.Fatalln(err)
	}

	log.Printf("Resp: \n%#v", resp)
```
I got empty struct GetStreamByChannelOutputType.
![image](https://user-images.githubusercontent.com/11390039/29497655-85c4ab42-85f4-11e7-84e8-8b916457e1df.png)
links[1] have right url for check stream.
If i use this url in postman i got right response.
![image](https://user-images.githubusercontent.com/11390039/29497668-be34c4ee-85f4-11e7-9a85-a46c1e57733a.png)

**Comment by edDimensi** [comment]
I think it's because you use old Accept Header.
If i use like you application/vnd.twitchtv.v3+json header, i got empty response. Need use v5.
Sorry for my english.

**Comment by edDimensi** [comment]
I try to change Accept Header 
`twitchSession.VersionHeader = "application/vnd.twitchtv.v5+json"`
but in code anyway using constant APIV3Header
https://github.com/knspriggs/go-twitch/blob/960df600bf2c90211a0261621709cc34fc0dc346/session.go#L63

**Comment by knspriggs** [comment]
Hi @edDimensi , thanks for checking out my library.

I see what your getting at, do you get the correct responses when you change the header in https://github.com/knspriggs/go-twitch/blob/960df600bf2c90211a0261621709cc34fc0dc346/constants.go#L7
?

**Comment by knspriggs** [comment]
Its certainly been a while since I've made any changes to this library, so it may need a bit of work.

**Comment by edDimensi** [comment]
Thx for fast answer. I do pr for this.
